### ISSUE TITLE
Resolve the warning when checking for epel release

### ISSUE THREAD

**Issue by abaiken** [quipucords/quipucords-installer#23]
In the epel role, there is still an error being thrown since we are using the `rpm` command. We should switch this to using `yum list` or something similar to resolve the error. 

```
TASK [epel : Check for EPEL rpm (RHEL/Centos)] *********************************
 [WARNING]: Consider using the yum, dnf or zypper module rather than running
'rpm'.  If you need to use command because yum, dnf or zypper is insufficient
you can add 'warn: false' to this command task or set 'command_warnings=False'
in ansible.cfg to get rid of this message.
```

**Comment by myersCody** [comment]
The ansible yum module has the ability to check if a package is installed. However, the return type may not match the returned that was previously given in the rpm check. 
```
- name: Check to see if EPEL is installed (RHEL/Centos)
  yum:
    name: epel-release
    state: installed
  register: have_epel_rpm_raw
  become: true
  ignore_errors: yes
  when:
    - have_rpm|bool
```
