### ISSUE TITLE
Convert docker role for online and common tasks

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#52]
**New Roles**
`install_docker_online`
`setup_docker`

----

- [ ] **Requirement One**: `install_docker_online` role

Move logic for install docker to the install docker online role. Remember that we are are no longer implementing the following logic:
```
If local rpm exists:
     install local rpm
else:
    Retrieve rpm from internet & install
```
Now all we want in the playbook is `Retrieve rpm from internet & install`. 

---
- [ ] **Requirement Two**: `setup_docker` role

Move all the logic for setting up docker into a common role.

--- 

- [ ] **Requirement Three**: Convert online install of docker for centos/rhel 6 into a yum command

The current docker role does a curl to get the rpm, and then does a rpm install of that rpm. This can be replaced with a yum install, because you can yum install from a url: 

```
- name: Obtain Docker Engine for (Centos/RHEL 6)
  get_url:
    url: http://yum.dockerproject.org/repo/main/centos/6/Packages/docker-engine-1.7.1-1.el6.x86_64.rpm
    dest: "{{ pkg_install_dir }}"
    mode: 0644
  when:
    - is_rhel_centos_6|bool
    - not have_docker
    - not find_docker_rpm_local

- name: Install Docker from local path (RHEL/Centos 6)
  shell: rpm -Uvh --force "{{find_docker_rpm_local_path}}"
  become: true
  when:
    - is_rhel_centos_6|bool
    - not have_docker
```
