### ISSUE TITLE
Convert qpc_cli into small sub-roles. 

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#54]
**New Roles**
`qpc_cli_online`
`qpc_cli_offline`
`qpc_cli`

----

- [ ] **Requirement One**: `qpc_cli_online` role

Remember that we are are no longer implementing the following logic:
```
If local rpm exists:
     install local rpm
else:
    Retrieve rpm from internet & install
```
Now all we want in online install task `Retrieve rpm from internet & install`. 

---
- [ ] **Requirement Two**: `qpc_cli_offline` role

Move logic related to local path stuff here. 

--- 
- [ ] **Requirement Two**: `qpc_cli` role
```
- name: Configure QPC to talk to server
  shell: qpc server config --host 127.0.0.1 --port "{{ server_port }}"
  when:
    - install_server|lower == 'true'
```
--- 

**Things to Remember:**
- Don't forget you already moved a lot of the `qpc_rpm_local_path` logic to the param validation & install prep so remove it from both online & offline
