### ISSUE TITLE
Make a copy of server image file instead of renaming

### ISSUE THREAD

**Issue by Dostonbek1** [quipucords/quipucords-installer#63]
In the `start_server_common` Ansible role, change this following task
```
- name: Rename Quipucords server docker image to version specific cache name
  command: mv "{{ pkg_install_dir }}{{ github_server_filename }}" "{{ qpc_server_version_filename }}"
  when:
    - not quipucords_docker_image_present
```

Instead of renaming the file, we want to make a copy of it so that when the Ansible roles are run for the second time the original file will still be there and will not error out.
