### ISSUE TITLE
Modify installer to reuse roles and more clearly document installation flows

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#68]
So the current way that we do it is if we want to implement different logic we are creating a new role to contain it.

Example:
```
├── qpc_server_common_prep
│   └── tasks
│       └── main.yml
├── qpc_server_offline
│   └── tasks
│       └── main.yml
├── qpc_server_offline_prep
│   └── tasks
│       └── main.yml
├── qpc_server_online
│   └── tasks
│       └── main.yml
├── qpc_server_online_prep
│   └── tasks
│       └── main.yml
├── qpc_server_start
│   └── tasks
│       └── main.yml
```

However, ansible roles will allow you to have more than one yml file in a role, the only requriement is that `main.yml` is always going to be the first one that is run.
Therefore we could restructure it to be more like:

```
└── qpc_server
     │   └── tasks
           ├── main.yml
           ├── qpc_server_prep.yml
           ├── qpc_server_offline_prep.yml
           ├── qpc_server_online_prep.yml
           ├── qpc_server_setup.yml
           ├── qpc_server_offline.yml
           ├── qpc_server_online.yml
           └── qpc_server_start.yml
```

Then the main.yml would look more like:
```
---

- name: online_install
   import_tasks: qpc_server_prep.yml
   import_tasks: qpc_server_online_prep.yml
   import_tasks: qpc_server_setup.yml
   import_tasks: qpc_server_online.yml
   import_tasks: qpc_server_start.yml
   when:
	- online install

- name: offline_install
   mport_tasks: qpc_server_offline_prep.yml
   import_tasks: qpc_server_prep.yml
   import_tasks: qpc_server_setup.yml
   import_tasks: qpc_server_offline.yml
   import_tasks: qpc_server_start.yml
   when:
	- offline install

```
Docs: https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
